language: python
python:
  - 2.6
  - 2.7
install:
    - pip install -r requirements.txt --use-mirrors
env:
    - DATABASE_URL='postgres://postgres:@localhost:5432/mobible'
before_script:
  - psql -c 'create database mobible;' -U postgres
script:
    - python manage.py test
